apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "dave" to read pods in the "development" namespace
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: development # This only grants permissions within the 'development' namespace
subjects:
- kind: User
  name: dave $ Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole  #This must be Role or ClusterRole
  name: secret-reader  # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
